# Generated by Django 5.0.6 on 2024-07-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=180, null=True, verbose_name="slug"
            ),
        ),
    ]
