# Generated by Django 5.0.6 on 2024-08-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_manufactured_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="version",
            options={
                "ordering": ["version_name", "version_number"],
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
            },
        ),
    ]
