# Generated by Django 5.0.6 on 2024-08-13 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_version_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                default=datetime.date(2024, 8, 13),
                help_text="Задайте дату производства продукта",
                verbose_name="Дата производства продукта",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Задайте номер версии",
                max_digits=10,
                verbose_name="Номер версии",
            ),
        ),
    ]
