# Generated by Django 5.1 on 2024-08-15 18:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_manufactured_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                default=datetime.date(2024, 8, 15),
                help_text="Задайте дату производства продукта",
                verbose_name="Дата производства продукта",
            ),
        ),
    ]
