# Generated by Django 5.1 on 2024-08-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_product_is_published_alter_product_manufactured_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["product_name", "category"],
                "permissions": [
                    ("can_cancel_publication", "Can cancel publication"),
                    ("can_edit_description", "Can edit description"),
                    ("can_edit_category", "Can edit category"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
